// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp0TVL1_IMzF_ywAU7VWkUajw-RYhS7E4',
    appId: '1:220012925043:web:372696a7c56d71bed65a06',
    messagingSenderId: '220012925043',
    projectId: 'learnforge-174ef',
    authDomain: 'learnforge-174ef.firebaseapp.com',
    storageBucket: 'learnforge-174ef.firebasestorage.app',
    measurementId: 'G-89Q9G21FNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4sSokm5cEqY92GZTdk49SWC-VAwok4yc',
    appId: '1:220012925043:android:d1c118b363e382efd65a06',
    messagingSenderId: '220012925043',
    projectId: 'learnforge-174ef',
    storageBucket: 'learnforge-174ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD619cWef5wx9pZ0oDPsd4SRU3npglMvks',
    appId: '1:220012925043:ios:96ff0124d7b7f39fd65a06',
    messagingSenderId: '220012925043',
    projectId: 'learnforge-174ef',
    storageBucket: 'learnforge-174ef.firebasestorage.app',
    iosBundleId: 'com.example.learnforgeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD619cWef5wx9pZ0oDPsd4SRU3npglMvks',
    appId: '1:220012925043:ios:96ff0124d7b7f39fd65a06',
    messagingSenderId: '220012925043',
    projectId: 'learnforge-174ef',
    storageBucket: 'learnforge-174ef.firebasestorage.app',
    iosBundleId: 'com.example.learnforgeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp0TVL1_IMzF_ywAU7VWkUajw-RYhS7E4',
    appId: '1:220012925043:web:79389e6196194469d65a06',
    messagingSenderId: '220012925043',
    projectId: 'learnforge-174ef',
    authDomain: 'learnforge-174ef.firebaseapp.com',
    storageBucket: 'learnforge-174ef.firebasestorage.app',
    measurementId: 'G-74Y2658SK9',
  );
}
